services:
  - type: web
    name: doc-analyzer
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        value: your-openai-key-here
      - key: PORT
        value: 10000
