services:
  - type: web
    name: doc-analyzer
    env: python
    region: oregon
    plan: free

    buildCommand: |
      ./render-build.sh
      pip install -r requirements.txt

    startCommand: ./start.sh

    envVars:
      - key: OPENAI_API_KEY
        value: your-real-openai-key
